### ISSUE TITLE
Hiding header hides menu button on mobile or with  "Always hide the sidebar" enabled, preventing sidebar from working.

### ISSUE THREAD

**Issue by gadgetchnnel** [maykar/kiosk-mode#29]
When hiding just the header, with the following config

```
kiosk_mode:
  hide_header: true
```
this also hides the menu button on mobile or if "Always hide the sidebar" option is enabled in the profile, like this:

![image](https://user-images.githubusercontent.com/2099542/98481494-801b3100-21f2-11eb-9ae2-5aa36ad2c533.png)

This prevents the sidebar from being able to be displayed, as this relies on the menu button.

The menu button is not hidden when on desktop browsers without the "Always hide the sidebar" option enabled in the profile, for example:

![image](https://user-images.githubusercontent.com/2099542/98481471-519d5600-21f2-11eb-977e-d3dd27dab297.png)

The menu button should not be hidden if the sidebar is not configured to be hidden.

**Comment by maykar** [comment]
Yes, this is expected behavior. The menu button is in the sidebar when it is visible, if the sidebar is not visible then the menu button exists in the header. So, if you hide the header then you also hide it's contents (which can sometimes include the menu button)

You can still swipe in from the left side of the screen to slide the sidebar in.
